### ISSUE TITLE
Change the algorithm to print time and memory

### ISSUE THREAD

**Issue by H4ad** [yamiteru/isitfast#34]
I have this output:

```
hash({}) 34,813 op/s (28,725 ns) ±1% x2,500 | 11,728 kB ±0.04% x25
fasterObjectHash({}) 80,103 op/s (12,484 ns) ±1% x2,500 | 7,984 kB ±0.06% x25
hash(singleObject) 18,910 op/s (52,881 ns) ±1% x2,500 | 18,088 kB ±0.03% x25
fasterObjectHash(singleObject) 60,713 op/s (16,471 ns) ±1% x2,500 | 15,040 kB ±0.03% x25
hash(tinyArray) 2,567 op/s (389,591 ns) ±1% x2,500 | 98,696 kB ±0.005% x25
fasterObjectHash(tinyArray) 9,900 op/s (101,012 ns) ±1% x2,500 | 99,952 kB ±0.005% x25
hash(mediumArray) 260 op/s (3.85e+3 ms) ±1% x2,500 | 907,408 kB ±0.0006% x25
fasterObjectHash(mediumArray) 1,050 op/s (952,360 ns) ±1% x2,500 | 939,296 kB ±0.0005% x25
hash(largeArray) 24 op/s (4.22e+4 ms) ±1% x2,500 | 4,287,489,176 kB ±1% x25
fasterObjectHash(largeArray) 78 op/s (1.29e+4 ms) ±1% x2,500 | 4,286,629,832 kB ±0.00001% x25
```

I think instead of `1.29e+4 ms`, would be better to show `128,20 ms`, and instead of `4,286,629,832 kb` show GB or MB (this number is very weird by the way).

If you have no problem in introducing two new deps, I found two libs that fit the requirements:

- [pretty-time](https://www.npmjs.com/package/pretty-time) to help on time prettify.
- [pretty-size](https://www.npmjs.com/package/pretty-bytes) to help on memory prettify

**Comment by yamiteru** [comment]
I had this feature on my TODO list so thanks for raising the question. I don't like deps so I'm gonna implement it myself. It's a very simple logic.

Regarding the absurdly big number of bytes. Can you create a reproduction for that? I wanna see what's going on there.

**Comment by H4ad** [comment]
I put the reproduction in the other PR: https://github.com/yamiteru/isitfast/issues/35#issue-1670033734
