### ISSUE TITLE
Feature Request: minimal terminal output

### ISSUE THREAD

**Issue by H4ad** [yamiteru/isitfast#4]
When I do performance improvements, I always do something like this: https://github.com/bendrucker/postgres-interval/pull/48
And I usually use benchmark.js because is very stable and have a nice output format:

```
satisfies(1.0.6, 1.0.3||^2.0.0) x 410,134 ops/sec ±1.64% (92 runs sampled)
satisfies(1.0.6, 2.2.2||~3.0.0) x 418,345 ops/sec ±1.10% (92 runs sampled)
satisfies(1.0.6, 2.3.0||<4.0.0) x 456,631 ops/sec ±1.23% (93 runs sampled)
```

Which is very easy to use and put in a PR, the current output today is:

```
satisfies(1.0.6, 1.0.3||^2.0.0, {"includePrelease":true,"loose":true,"rtl":true}) 434,027 op/s [-1, +0.9]% (130,000 cycles)
                                                                                  1,344 Kb [-1, +1]% (25 cycles)

satisfies(1.0.6, 2.2.2||~3.0.0, {"includePrelease":true,"loose":true,"rtl":true}) 470,809 op/s [-1, +1]% (100,000 cycles)
                                                                                  1,344 Kb [-1, +1]% (25 cycles)

satisfies(1.0.6, 2.3.0||<4.0.0, {"includePrelease":true,"loose":true,"rtl":true}) 501,504 op/s [-1, +1]% (100,000 cycles)
                                                                                  1,296 Kb [-1, +1]% (25 cycles)
```

If we mix long names with short names:

```
satisfies(1.0.6, 1.0.3||^2.0.0)                                                   462,107 op/s [-1, +0.6]% (110,000 cycles)
                                                                                  1,264 Kb [-1, +1]% (25 cycles)

satisfies(1.0.6, 2.2.2||~3.0.0)                                                   475,059 op/s [-1, +0.9]% (110,000 cycles)
                                                                                  1,344 Kb [-1, +1]% (25 cycles)

satisfies(1.0.6, 2.3.0||<4.0.0)                                                   506,585 op/s [-1, +0.9]% (110,000 cycles)
                                                                                  1,296 Kb [-1, +1]% (25 cycles)
```

The terminal is very nice but to document is not that great, if we have the option to change between implementations, it will be very good.

**Comment by yamiteru** [comment]
Hmm so if I understand you correctly you'd like an output similar to benchmark.js, meaning a one-liner.

**Comment by H4ad** [comment]
@yamiteru Exactly, maybe we can switch the implementation like: `useTerminal('simple')`.

**Comment by yamiteru** [comment]
I don't like when functions do more things depending on the input. I like when things are explicit.

So I've been thinking about something like `useTerminal` and `useTerminalCompact`. They're probably gonna share most of the code.

Also do you have any idea how to transform [-1, +0.9]% into ±N%? Should we choose the biggest number? Or do an average of those two numbers?

**Comment by H4ad** [comment]
Hm... maybe you can put it directly: 

`satisfies(1.0.6, 1.0.3||^2.0.0) 462,107 op/s (-1%, +0.6%) (110,000 cycles) 1,264 Kb (-1%, +1%) (25 cycles)`

Also, I don't know how you calculate the variance but benchmark.js uses standard deviation:
https://github.com/bestiejs/benchmark.js/blob/main/benchmark.js#L1912-L1936

**Comment by yamiteru** [comment]
Yeah I guess we can provide both the same way we do it now.

Currently I'm basically just doing `min / median` and `median / max`.

I'm gonna change it to standard deviation for sure!

**Comment by yamiteru** [comment]
So I've done some digging and based on [Robust measures of scale](https://en.wikipedia.org/wiki/Robust_measures_of_scale) and [Deviation (statistics)
](https://en.wikipedia.org/wiki/Deviation_(statistics)) I've decided to use [Median absolute deviation
](https://en.wikipedia.org/wiki/Median_absolute_deviation) since it's more statistically robust and meaningful.

Thanks to this I don't need to get `min` and `max` anymore and my denoising algorithm which waits until V8 warms up until deviation of `rangePercent` is achieved can now use this much more robust median absolute deviation making the whole denoising algorithm more robust.

But because of that there's quite a lot of changes so it's gonna take me a few days to finish this feature request.

**Comment by H4ad** [comment]
@yamiteru Take your time, thanks for your hard work.
